### ISSUE TITLE
Bug: Bad Values from Purifying Fitness Factors

### ISSUE THREAD

**Issue by cswarth** [santa-dev/santa-sim#11]
`AbstractSiteFitness.getLogFitnessChange()` and `PurifyingFitnessFactor.setFitnesses()` together establish policies that can result in mathematically meaningless fitness values.  Specifically, it is possible to generate a genome fitness value of NaN as the result of summing -Infinity and +Infinity when a codon mutates from STOP to non-STOP residue.  Genomes with NaN fitness values are not detected as exceptions and will persist in the simulated population.  A simulated lineages in which genome fitness values go to NaN looks like this:
![screen shot 2016-02-08 at 6 32 43 pm](https://cloud.githubusercontent.com/assets/295428/12958820/5c1e63f0-cfe8-11e5-89e9-6c63006ffb71.png)

The problem occurs in-part because of an optimization in `AbstractSiteFitness.getLogFitnessChange()` that does not check the position of a mutation against the list of sites covered by a fitness factor.  Instead, this routine assumes that sites not covered by a fitness factor have fitness value of zero (neutral fitness). 

[getLogFitnessChange](https://github.com/santa-dev/santa-sim/blob/c938be4ceb7ea26c1740a1ad5f75c4ed6f5f91ed/src/santa/simulator/fitness/AbstractSiteFitnessFactor.java#L48)
```
    public double getLogFitnessChange(StateChange change) {
	    // we ignore the sites list here because it is probably cheaper to look
	    // up in the table and get a zero change than check the site list.
	    // It does mean the logFitness array should have zeros in sites that
	    // are not handled by this factor.
        return logFitness[change.position][change.newState] - logFitness[change.position][change.oldState];
    }
```

That would be a valid optimization if it weren't for code in `PurifyingFitnessFactor.setFitnesses()` which violates the assumption of zero fitness at sites not covered by the factor. 

[setFitnesses](https://github.com/santa-dev/santa-sim/blob/c938be4ceb7ea26c1740a1ad5f75c4ed6f5f91ed/src/santa/simulator/fitness/PurifyingFitnessFactor.java#L59)
```
	            // stop codons are given a logFitness of -Inf
	            logFitness[i][stateSize] = Double.NEGATIVE_INFINITY;
```

`PurifyingFitnessFactor.setFitnesses()` tries to implement a policy that any in-frame STOP codon introduced into an amino acid feature is a lethal mutation.  (The implementation of this policy rests on the assumption that features begin in-frame.) This implementation is flawed in two ways: First it violates the assumption made in `AbstractSiteFitness.getLogFitnessChange()` that 'the logFitness array should have zeros in sites that are not handled by this factor.'  Second, because it does not discriminate by feature alphabet, it also ensure any mutation to a 'T' in a nucleotide-denominated feature to be a lethal mutation!

## The Fix

`PurifyingFitnessFactor.setFitnesses()` must only set `logFitness[i][stateSize]` if it is initializing a factor defined on an amino-acid-denominated feature. 

`AbstractSiteFitness.getLogFitnessChange()` must check that a mutation falls within the bounds of a fitness factor before applying the fitness value.

## Unintended Consequences

Checking the mutation position will have a small but detrimental effect on performance.  This will also restrict sensitivity to STOP codons to positions explicitly covered by a fitness factor, rather than at every position in a feature.  This will result in a visible change in behavior.

**Comment by matsen** [comment]
Fantastic report, and it sounds like a great plan.

**Comment by cswarth** [comment]
I've had more time to delve into exactly why this bug occurs and the ultimate cause is a little different than I thought.  One obvious question is if this bug was tickled by a stop codon within a feature mutating to a non-stop codon, why were those genomes in the population to begin with if stop codons are lethal?   The answer is that fitness is claculated a little differently during initialization of the population than it is after a mutation.

Recall that fitness factors are defined on features, and a fitness factor does not have to cover an entire feature.  Factors often cover only a couple of residues or nucleotides with a feature.   During initialization of the population, fitness is calculated over fitness factors. [`computeLogFitness(Genome genome)`](https://github.com/santa-dev/santa-sim/blob/master/src/santa/simulator/fitness/FitnessFunction.java#L121)    Anything falling outside a factor is not considered for the initial calculation of genome fitness. Any genome that has a stop codon within a factor will get `-Infinity` fitness and will be excluded from the next generation.  

However there may be stop codons within a feature but outside of a factor.  Those genomes will reproduce and eventually one of the stop codons mutates to a non-stop.   When fitness is updated after a mutation, changes to the fitness value are extracted from a precomputed cache.  Unlike during initialization, every position in the feature is checked for a change in fitness regardless of whether a factor is defined on that region or not. [getLogFitnessChange(StateChange change)](https://github.com/santa-dev/santa-sim/blob/master/src/santa/simulator/fitness/AbstractSiteFitnessFactor.java#L48)    This is meant to be an optimization and relies upon the assumption that regions outside a factor have neutral fitness.   

It was this assumption that PurifyingFitness was violating.  It assigned `-Inifinity` fitness to any stop codon anywhere in the feature, not just within the region covered by the fitness factor.    The most parsimonious fix is to only assign `-Infinity` fitness to sites within a factor.   There is no need to check each mutation against the bounds of factors before updating fitness.  

That was the fix implemented in commit d9ac9c5 and it seems to be working well.

**Comment by cswarth** [comment]
Reopening b/c Erick suggests leaving in the restriction on in-frame stop codons across features regardless of an overlapping fitness factor.  To do that we would still assign `-Infinity` fitness to all sites in a  feature and modify `computeLogFitness(Genome genome)`  to consider all sites in a feature (and not restrict to just factors) when calculating the initial fitness of a genome.

**Comment by matsen** [comment]
:dancers:
