### ISSUE TITLE
link in README is broken

### ISSUE THREAD

**Issue by maxbiostat** [santa-dev/santa-sim#12]
link to fitness functions is broken

**Comment by cswarth** [comment]
Don't know why this isn't being [closed via commit](https://help.github.com/articles/closing-issues-via-commit-messages/), but 97845d0 fixed this issue.

**Comment by maxbiostat** [comment]
don't forget to do a PR from your branch, though. Currently the version at santa-dev/santa-sim is still broken [that's probably why it didn't close on commit, since the commit belongs to your fork]..

**Comment by cswarth** [comment]
Thanks!  PR merged.
