### ISSUE TITLE
The README should describe indels

### ISSUE THREAD

**Issue by matsen** [santa-dev/santa-sim#14]

**Comment by cswarth** [comment]
README has the following paragraph.  There is more detailed info in the documentation [in the wiki](https://github.com/santa-dev/santa-sim/wiki/Indels).


> In addition to substitution mutations, the user may also configure indel processes that change the length of a simulated genome. It is assumed that frame-shifting a genome is nearly always fatal so only whole-codon indels are permitted. Independent proability distributions control the frequency of insertions and deletions, and another distribution controls the length of the indel. When indels overlap regions on which fitness functions are defined, the regions may grow or shrink, or even become fragmented. As with substitution mutations, indels will affect subsequent generations of the lineage but will not affect sibling lineages.

**Comment by matsen** [comment]
👍
