### ISSUE TITLE
ant fails to build

### ISSUE THREAD

**Issue by abbasjariani** [santa-dev/santa-sim#18]
Hi,

Sorry for opening an issue rather than helping in closing one. But hopefully I'll get to that stage soon enough.
When I try to build the project by ant I get the following message. 
```

abbas@abbas-desktop:~/mySoft/SANTAsim/santa-sim$ ant
Buildfile: /home/abbas/mySoft/SANTAsim/santa-sim/build.xml

resolve:

BUILD FAILED
/home/abbas/mySoft/SANTAsim/santa-sim/build.xml:25: Problem: failed to create task or type antlib:org.apache.ivy.ant:retrieve
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
No types or tasks have been defined in this namespace yet

This appears to be an antlib declaration. 
Action: Check that the implementing library exists in one of:
        -/usr/share/ant/lib
        -/home/abbas/.ant/lib
        -a directory added on the command line with the -lib argument


Total time: 0 seconds


```

**Comment by abbasjariani** [comment]
The answer in [this stackoverflow](http://stackoverflow.com/questions/12677816/ant-target-failing-antlib-or-ivy-issue) question solved the issue. I manually downloaded and copied the ivy-2.4.0.jar to ant's lib directory.

**Comment by cswarth** [comment]
I think you're right, this is a bug.  The behavior you observed is not what is supposed to happen.  

`build.xml` has an `install-ivy` target that is supposed to automatically install `ivy.jar` if you don't already have it.  That doesn't seem to have happened in your case but that's what's supposed to happen.  I'll take a look.

**Comment by cswarth** [comment]
I hadn't yet pushed the changes to `build.xml` that let Ivy initialize itself.  Now the repo is updated, `ant` should take care of downloading and installing Ivy for you.  If it is necessary to download the Ivy jar file, `Ant` will request that you restart the build again because it needs to load the Ivy jar file at startup.
