### ISSUE TITLE
Performance of Roulette Wheel Selector

### ISSUE THREAD

**Issue by rambaut** [santa-dev/santa-sim#27]
It would be good to do some profiling but I suspect the selection of the new generation proportional to their fitness will be a major performance bottle neck. 

Currently this is done in SimpleRouletteWheelSelector. selectParents(). An array of cumulative fitnesses for each of the parents is created and normalized to sum to 1. Then a random number 0,1 is drawn and the algorithm then walks through the fitnesses until the RNG > than the cumulative fitness.

This might be speeded up by creating a binary search tree to find the RNG location in the fitness array. It could also be threaded to get parallelization.

**Comment by abbasjariani** [comment]
BinarySearchSelector (binary search algorithm) was implemented to replace the SimpleRouletteWheelSelector. The output of binary search is checked to be identical to the SimpleRouletteWheelSelector however it clearly goes faster. Will do some profiling for the next step.
