### ISSUE TITLE
infinite loop in pruneDeadLineages()

### ISSUE THREAD

**Issue by fredjaya** [santa-dev/santa-sim#30]
Hi,

We've encountered a bug when initialising with our own sequence alignment, where the program stalls after commencing the second (sometimes third) replicate. 

@koadman has run the simulation in eclipse debugger and came across an infinite loop in pruneDeadLineages(), possibly associated with nodes that reference parents from later generations, creating a cycle.

The alignment and xml files used are [attached](https://github.com/santa-dev/santa-sim/files/3040928/fj_santatest2.zip).

Thanks!

**Comment by koadman** [comment]
this is a showstopper for us so would be great if someone on the dev team could take a look!

**Comment by gertjan** [comment]
Thank you for providing the attached data. It made it a lot easier to reproduce, debug and fix the issue.

As I have not been involved in the development for some time, I opted for a rather quick fix but the above commit should suffice to fix the infinite loops.

**Comment by koadman** [comment]
thanks, glad it was a simple fix. seems to work. ok to close
