### ISSUE TITLE
Validation: positive selective sweeps should make a v-shaped distribution of diversity around the selected site as in Neher review

### ISSUE THREAD

**Issue by matsen** [santa-dev/santa-sim#7]
![image](https://cloud.githubusercontent.com/assets/112708/11010938/31c8d9d2-84b1-11e5-9308-70194cd59fdf.png)

**Comment by matsen** [comment]
This is done, no?

**Comment by cswarth** [comment]
Selective sweep with recombination demonstrated in [santa-sweep](https://github.com/cswarth/santa-sweep) repository.
