### ISSUE TITLE
Validation: check that selection is working via dN/dS calculation

### ISSUE THREAD

**Issue by matsen** [santa-dev/santa-sim#8]
@cswarth already has this going, but just to record it.

**Comment by cswarth** [comment]
This work is archived in the [santa-dnds repo](https://github.com/cswarth/santa-dnds)

Looking for evidence of simulated selective pressure by plotting dN/dS ratios calculated from sequences samples at multiple time points under various fitness functions and fitness strengths.

dN/dS is calculated by `codeml` as a single ML ratio at all branches on a tree.

`noselection` is an empirical fitness function with uniform fitness values for all residues.

`purifyingfitness` is a purifying fitness with a linear decay across chemically similar residues.  

`purifyingvalues` is an empirical fitness that explicitly assigns values to inividual residues to favor only one amino acid across the genome.

![screen shot 2016-08-18 at 2 24 02 pm](https://cloud.githubusercontent.com/assets/295428/17791344/8718f3ca-654f-11e6-905c-1f5c7e514460.png)

**Comment by cswarth** [comment]
After discussing with Erick, the plan is to relabel these categories to better reflect the actual selection criteria being used in the santa config file.   I also need to follow up and make sure the graphing package I'm using (bokeh) is accurately reflecting the correct labeling.  

For purifying selection with linear decay, we have too many things that can very, including the chemical grouping of residues, the slope of the linear decay, and the value of the low-fitness plateau.  Try testing with a flat plateau up top (no linear decay) and just vary the value of the low-fitness plateau between low and high values.

The `purifyingvalues` (which is really an EmpiricalFitness with explicit fitness values for each residue) is only favoring one particular amino acid out of 20, so there is a lot of wandering until the high-fitness amino acid happens to be chosen.  Try comparing the behavior of a homogenous genome with a heterogenous genome to see whether that provides a stronger signal in dn/ds.

**Comment by cswarth** [comment]
An ongoing analysis of Santa selection performance as measured by dN/dS ratios is available under the github repo https://github.com/cswarth/santa-dnds

The top-level README in that repo describes the methodology and results.  Some analysis is ongoing, but it is clear that fitness constraints in SANTA are functional and behave in a manner largely consistent with the documentation.

Also an empirical demonstration of fitness selection can be seen as part of the selective sweep with recombination repo at https://github.com/cswarth/santa-sweep
